// Films
export const SET_FILMS = "SET_FILMS";
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";

// Users
export const CREATE_NEW_ACCOUNT = "CREATE_NEW_ACCOUNT";
export const SET_CURRENT_ACCOUNT = "SET_CURRENT_ACCOUNT";
export const REMOVE_CURRENT_ACCOUNT = "REMOVE_CURRENT_ACCOUNT";
export const ADD_FAVORITE_FILM = "ADD_FAVORITE_FILM";
export const REMOVE_FAVORITE_FILM_BY_ID = "REMOVE_FAVORITE_FILM_BY_ID";



